# Be sure to restart your server when you modify this file.
 
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
 
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
 
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
 
development:
  secret_key_base: 1f0e3b5f0e553ab54fbc35c6423d7ca94e344ff338f020e740a3b80582cda13b94a708ba8ebfc28edb3719cf1a259cee87f5c5e114287662fe89340358776087
 
test:
  secret_key_base: b750c713f2f9fc9b59aad33167ccb27c35917010991613de25c95b00711f44a7a330b4b74b5413684a890d0d550049b080335c372c656c55271ebfcd5cd3461d
 
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
